### ISSUE TITLE
Jira collector issue: Not showing any teams on UI Configure Feature Widget

### ISSUE THREAD

**Issue by khurshid4** [capitalone/Hygieia#1915]
Hello,
I am trying to setup a Jira collector using below steps.
1) Mongo db server started
2) I have start api jar.
3) And start jira_collector.jar.
And database name also same like dashboarddb in "api jar "and "jira_collector.jar" properties.
but not showing jira on UI Configure Feature Widget
I have also attached screenshot for UI Configure Feature Widget and jira collector runing status.

![ui](https://user-images.githubusercontent.com/34913344/34466504-e070d244-eefb-11e7-9ba2-9d407ef0fd3f.png)
![jira](https://user-images.githubusercontent.com/34913344/34466505-e71d5950-eefb-11e7-8f33-572c4b99d32e.png)

Thanks

**Comment by khurshid4** [comment]
I have fixed this issue by changing some jira collector properties. I have mention in below.

dbname=dashboarddb
dbhost=127.0.0.1
dbport=27017
dbusername=hygieia
dbpassword=hygieia
logging.file=./logs/jira.log
feature.pageSize=100
feature.deltaStartDate=2016-03-01T00:00:00.000000
feature.masterStartDate=2016-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2016-03-01T00:00:00.000000
feature.cron=0 * * * * *
feature.queryFolder=jiraapi-queries
feature.storyQuery=story
feature.epicQuery=epic
feature.jiraBaseUrl=http://localhost:8080
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=*********************
feature.jiraOauthAuthtoken=
feature.jiraOauthRefreshtoken=
feature.jiraOauthRedirecturi=
feature.jiraOauthExpiretime=
feature.jiraIssueTypeNames=Story
feature.jiraSprintDataFieldName=customfield_10000
feature.jiraEpicIdFieldName=customfield_10002
feature.jiraStoryPointsFieldName=customfield_10003
feature.jiraTeamFieldName=

**Comment by praveenkanna** [comment]
Hi @khurshid4 I'm facing the same issue that not able to see Jira widget configuration.. can you please help me how did you get the data ?

**Comment by khurshid4** [comment]
Hello @praveenkanna ,

This issue related to configuration of properties file.So check your properties in the properties file, I have 
also mention in above, can be used as it is.

**Comment by praveenkanna** [comment]
@khurshid4 yeah i have rechecked my properties everything is present but still not able to see the dropdown in jira! could you help me in setting up .

**Comment by khurshid4** [comment]
@praveenkanna 
These properties only use for which is required in your configuration.
Please try above properties in your configuration and remove other once.

**Comment by pk277** [comment]
@khurshid4 

I am running into the similar issue. i have used the properties file given by you but still not able to see any data source in feature widget.

Any other changes have you made to make it work ?

Thanks
