### ISSUE TITLE
What are the required config for Jira collector

### ISSUE THREAD

**Issue by hongluovz** [capitalone/Hygieia#220]
I provided two main config lines in application.properties:
"feature.jiraBaseUrl=http://jira.mycompany.com
feature.jiraCredentials=my_jira_username:my_password"

I got this error when starting the jira collector. What would be the root cause of this error. Thanks.
"2015-12-14 09:45:00,000 INFO  c.c.d.collector.CollectorTask - Running Collector: Jira
2015-12-14 09:45:00,012 INFO  c.c.d.collector.FeatureCollectorTask - Starting Feature collection...
2015-12-14 09:45:00,125 ERROR c.c.d.c.team.TeamDataClientSetupImpl - There was a problem retrieving or parsing data from the local repository while retrieving a max change date
Returning null
2015-12-14 09:45:00,137 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at com.capitalone.dashboard.util.FeatureWidgetQueries.getQuery(FeatureWidgetQueries.java:66) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:131) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:99) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:25) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:62) ~[core-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_80]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_80]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_80]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [na:1.7.0_80]"

**Comment by softwareklinic** [comment]
https://github.com/capitalone/Hygieia/issues/218 - check this issue - we pretty much configured all the options provided in the sample application.properties for jira collector... but after that ... jira feature collector was giving error for some query - for which we changed the code in jira feature collector... and it was collecting the data... but then again the same or similar issue on the Jira Widget in Hygieia UI... so we are waiting for the error to be clarified./explained/addressed in issue # 218 posted by my colleague...

https://github.com/capitalone/Hygieia/issues/218

**Comment by amp5208** [comment]
@softwareklinic , Thank you for reaching out regarding your use of the Jira Feature Collector.  Assuming that your access is sufficient to pull all Jira data, the following error message:

<pre>There was a problem retrieving or parsing data from the local repository while retrieving a max change date</pre>

Indicates that your MongoDB collector database for Jira is missing content that would be pulled via the following method chain:  <code>projectRepo.getProjectMaxChangeDate(featureCollectorRepository.findByName("Jira").getId(),featureSettings.getDeltaStartDate());</code>

To me, this seems that either there are no available change date values generated in your Jira Collector MongoDB collection (less likely), or you are missing a start-date-related property setting for the feature context in your application.properties file (more likely).  Can you confirm if you have a delta start date property in your application.properties?

**Comment by hongluovz** [comment]
I have this default value:
feature.deltaCollectorItemStartDate=2008-01-01T00:00:00.000000, so I need change it. Thanks

**Comment by hongluovz** [comment]
I have these config now, but still get the same error. Thanks.
feature.deltaCollectorItemStartDate=2013-08-01T00:00:00.000000
feature.deltaStartDate=2015-08-01T00:00:00.000000
feature.masterStartDate=2015-12-01T00:00:00.000000

**Comment by amp5208** [comment]
You may not have Jira data as far back as 2013, and may account for an error.  Please attempt more recent start date configurations and let me know if you see any change.  If not, I will have to look into this further.

**Comment by amitmawkin** [comment]
I built it without the bad dependency the collector has other errors,

[jmdaboa@ccloud-tomcat04200 dashboard]$ /opt/beasys/bea1036/jdk1.8.0_25/bin/java -jar /prod/msp/domains/dashboard/versionone-feature-collector.jar --spring.config.name=versionone --spring.config.location=/prod/msp/domains/dashboard/versionone.properties
21:33:23,852 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
21:33:23,855 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
21:33:23,855 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/prod/msp/domains/dashboard/versionone-feature-collector.jar!/logback.xml]
21:33:23,903 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@321a6e3e - URL [jar:file:/prod/msp/domains/dashboard/versionone-feature-collector.jar!/logback.xml] is not of type file
21:33:24,013 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
21:33:24,032 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
21:33:24,059 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
21:33:24,187 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
21:33:24,377 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
21:33:24,387 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ROLLING]
21:33:24,494 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - No compression will be used
21:33:24,496 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy - Will use the pattern /prod/msp/logs/dashb_logs/dashb-app-log-%d{yyyy-MM-dd}.%i.txt for the active file
21:33:24,500 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@352d194 - The date pattern is 'yyyy-MM-dd' from file name pattern '/prod/msp/logs/dashb_logs/dashb-app-log-%d{yyyy-MM-dd}.%i.txt'.
21:33:24,500 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@352d194 - Roll-over at midnight.
21:33:24,504 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@352d194 - Setting initial period to Tue Dec 15 21:33:24 EST 2015
21:33:24,506 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
21:33:24,506 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - Active log file name: /prod/msp/logs/dashb_logs/dashb-app-log-2015-12-15.0.txt
21:33:24,506 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - File property is set to [null]
21:33:24,508 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - Failed to create parent directories for [/prod/msp/logs/dashb_logs/dashb-app-log-2015-12-15.0.txt]
21:33:24,508 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[ROLLING] - openFile(null,true) call failed. java.io.FileNotFoundException: /prod/msp/logs/dashb_logs/dashb-app-log-2015-12-15.0.txt (No such file or directory)
at java.io.FileNotFoundException: /prod/msp/logs/dashb_logs/dashb-app-log-2015-12-15.0.txt (No such file or directory)
at at java.io.FileOutputStream.open(Native Method)
at at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
at at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
at at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:148)
at at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
at at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:86)
at at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
at at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
at at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
at at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
at at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
at at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
at at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:77)
at at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:152)
at at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
at at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
at at org.slf4j.LoggerFactory.bind(LoggerFactory.java:141)
at at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:120)
at at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:331)
at at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:283)
at at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
at at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
at at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
at at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:160)
at at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
at at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
at at com.capitalone.dashboard.Application.main(Application.java:21)
at at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at at java.lang.reflect.Method.invoke(Method.java:483)
at at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
at at java.lang.Thread.run(Thread.java:745)
21:33:24,508 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
21:33:24,509 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ROLLING] to Logger[ROOT]
21:33:24,510 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
21:33:24,510 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
21:33:24,512 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@499d0974 - Registering current configuration as safe fallback point

_    _             _      _           __      __           _              ____             ______         _                   _____      _ _           _
| |  | |           (_)    (_)          \ \    / /          (_)            / __ \           |  ____|       | |                 / ____|    | | |         | |
| |__| |_   _  __ _ _  ___ _  __ _ _____\ \  / /__ _ __ ___ _  ___  _ __ | |  | |_ __   ___| |__ ___  __ _| |_ _   _ _ __ ___| |     ___ | | | ___  ___| |_ ___  _ __
|  __  | | | |/ _` | |/ _ \ |/ _` |______\ \/ / _ \ '__/ __| |/ _ \| '_ \| |  | | '_ \ / _ \  __/ _ \/ _` | __| | | | '__/ _ \ |    / _ \| | |/ _ \/ __| __/ _ \| '__|
| |  | | |_| | (_| | |  __/ | (_| |       \  /  __/ |  \__ \ | (_) | | | | |__| | | | |  __/ | |  __/ (_| | |_| |_| | | |  __/ |___| (_) | | |  __/ (__| || (_) | |
|_|  |_|\__, |\__, |_|\___|_|\__,_|        \/ \___|_|  |___/_|\___/|_| |_|\____/|_| |_|\___|_|  \___|\__,_|\__|\__,_|_|  \___|\_____\___/|_|_|\___|\___|\__\___/|_|
        __/ | __/ |
       |___/ |___/

2015-12-15 21:33:25,250 INFO  com.capitalone.dashboard.Application - Starting Application v1.5.0-SNAPSHOT on ccloud-tomcat04200.kdc.capitalone.com with PID 61491 (/prod/msp/domains/dashboard/versionone-feature-collector.jar started by jmdaboa in /prod/msp/domains/dashboard)
2015-12-15 21:33:25,314 INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@4953e524: startup date [Tue Dec 15 21:33:25 EST 2015]; root of context hierarchy
2015-12-15 21:33:26,818 INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2015-12-15 21:33:26,971 INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService  'taskScheduler'
2015-12-15 21:33:27,046 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: ccloud-tomcat04200.kdc.capitalone.com:11500
2015-12-15 21:33:27,141 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[ccloud-tomcat04200.kdc.capitalone.com:11500], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2015-12-15 21:33:27,226 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@c346accf, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=0, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@24c47201, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@5c74700e, socketFactory=javax.net.DefaultSocketFactory@60e67fd2, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2015-12-15 21:33:27,613 INFO  org.mongodb.driver.cluster - No server chosen by PrimaryServerSelector from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, all=[ServerDescription{address=ccloud-tomcat04200.kdc.capitalone.com:11500, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
2015-12-15 21:33:27,791 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:1, serverValue:1583}] to ccloud-tomcat04200.kdc.capitalone.com:11500
2015-12-15 21:33:27,792 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=ccloud-tomcat04200.kdc.capitalone.com:11500, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 1]}, minWireVersion=0, maxWireVersion=3, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=982963}
2015-12-15 21:33:27,842 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:1584}] to ccloud-tomcat04200.kdc.capitalone.com:11500
2015-12-15 21:33:28,390 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: ccloud-tomcat04200.kdc.capitalone.com:11500
2015-12-15 21:33:28,391 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[ccloud-tomcat04200.kdc.capitalone.com:11500], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2015-12-15 21:33:28,392 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@c346accf, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=0, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@24c47201, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@5c74700e, socketFactory=javax.net.DefaultSocketFactory@60e67fd2, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2015-12-15 21:33:28,403 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: ccloud-tomcat04200.kdc.capitalone.com:11500
2015-12-15 21:33:28,403 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[ccloud-tomcat04200.kdc.capitalone.com:11500], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2015-12-15 21:33:28,404 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@c346accf, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=0, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@24c47201, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@5c74700e, socketFactory=javax.net.DefaultSocketFactory@60e67fd2, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2015-12-15 21:33:28,440 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:3, serverValue:1585}] to ccloud-tomcat04200.kdc.capitalone.com:11500
2015-12-15 21:33:28,440 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=ccloud-tomcat04200.kdc.capitalone.com:11500, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 1]}, minWireVersion=0, maxWireVersion=3, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=477444}
2015-12-15 21:33:28,460 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:4, serverValue:1586}] to ccloud-tomcat04200.kdc.capitalone.com:11500
2015-12-15 21:33:28,461 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=ccloud-tomcat04200.kdc.capitalone.com:11500, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 1]}, minWireVersion=0, maxWireVersion=3, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=603020}
2015-12-15 21:33:28,720 INFO  c.c.dashboard.config.MongoConfig - Initializing Mongo Client server at: ccloud-tomcat04200.kdc.capitalone.com:11500
2015-12-15 21:33:28,722 INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[ccloud-tomcat04200.kdc.capitalone.com:11500], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2015-12-15 21:33:28,730 INFO  c.c.dashboard.config.MongoConfig - Connecting to Mongo: Mongo{options=MongoClientOptions{description='null', readPreference=primary, writeConcern=WriteConcern{w=1, wtimeout=0, fsync=false, j=false, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@c346accf, minConnectionsPerHost=0, maxConnectionsPerHost=100, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=0, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=false, sslEnabled=false, sslInvalidHostNamesAllowed=false, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@24c47201, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@5c74700e, socketFactory=javax.net.DefaultSocketFactory@60e67fd2, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=100, minSize=0, maxWaitQueueSize=500, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=false, receiveBufferSize=0, sendBufferSize=0}}}
2015-12-15 21:33:28,763 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:5, serverValue:1587}] to ccloud-tomcat04200.kdc.capitalone.com:11500
2015-12-15 21:33:28,766 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=ccloud-tomcat04200.kdc.capitalone.com:11500, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 1]}, minWireVersion=0, maxWireVersion=3, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=2288809}
2015-12-15 21:33:29,405 INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
2015-12-15 21:33:29,415 INFO  com.capitalone.dashboard.Application - Started Application in 4.645 seconds (JVM running for 6.079)
2015-12-15 21:34:05,001 INFO  c.c.d.collector.CollectorTask - Running Collector: VersionOne
2015-12-15 21:34:05,017 INFO  c.c.d.collector.FeatureCollectorTask - Starting Feature collection...
2015-12-15 21:34:05,279 ERROR c.c.d.c.team.TeamDataClientSetupImpl - There was a problem retrieving or parsing data from the local repository while retrieving a max change date
Returning null
org.springframework.data.mongodb.UncategorizedMongoDbException: Query failed with error code 17287 and error message 'Can't canonicalize query: BadValue unknown top level operator: $query' on server ccloud-tomcat04200.kdc.capitalone.com:11500; nested exception is com.mongodb.MongoQueryException: Query failed with error code 17287 and error message 'Can't canonicalize query: BadValue unknown top level operator: $query' on server ccloud-tomcat04200.kdc.capitalone.com:11500
at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:101) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2013) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1896) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1707) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1690) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:602) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.repository.query.AbstractMongoQuery$Execution.readCollection(AbstractMongoQuery.java:170) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.repository.query.AbstractMongoQuery$CollectionExecution.execute(AbstractMongoQuery.java:193) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:104) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:454) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:432) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at com.sun.proxy.$Proxy41.getTeamMaxChangeDate(Unknown Source) ~[na:na]
at com.capitalone.dashboard.client.team.TeamDataClientSetupImpl.getMaxChangeDate(TeamDataClientSetupImpl.java:193) ~[versionone-feature-collector.jar!/:1.5.0-SNAPSHOT]
at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:140) [versionone-feature-collector.jar!/:1.5.0-SNAPSHOT]
at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:105) [versionone-feature-collector.jar!/:1.5.0-SNAPSHOT]
at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [versionone-feature-collector.jar!/:1.5.0-SNAPSHOT]
at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_25]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_25]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_25]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_25]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: com.mongodb.MongoQueryException: Query failed with error code 17287 and error message 'Can't canonicalize query: BadValue unknown top level operator: $query' on server ccloud-tomcat04200.kdc.capitalone.com:11500
at com.mongodb.connection.ProtocolHelper.getQueryFailureException(ProtocolHelper.java:93) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.connection.QueryProtocol.receiveMessage(QueryProtocol.java:288) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:229) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:38) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:155) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:219) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.connection.DefaultServerConnection.query(DefaultServerConnection.java:166) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.operation.FindOperation$1.call(FindOperation.java:397) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.operation.FindOperation$1.call(FindOperation.java:394) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:195) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:168) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.operation.FindOperation.execute(FindOperation.java:394) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.operation.FindOperation.execute(FindOperation.java:57) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.Mongo.execute(Mongo.java:738) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.Mongo$2.execute(Mongo.java:725) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.DBCursor.initializeCursor(DBCursor.java:815) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.DBCursor.hasNext(DBCursor.java:149) ~[mongo-java-driver-3.0.2.jar!/:na]
at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1882) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
... 29 common frames omitted
teaminfo.st 1:36: \n in string
teaminfo.st 2:7: \n in string
teaminfo.st 3:7: \n in string
teaminfo.st 4:13: \n in string
teaminfo.st 5:13: \n in string
teaminfo.st 6:12: \n in string
teaminfo.st 7:7: \n in string
teaminfo.st 8:28: \n in string
teaminfo.st 9:39: \n in string
2015-12-15 21:34:06,315 ERROR c.c.d.c.team.TeamDataClientSetupImpl - Unexpected error in VersionOne paging request of java.lang.ClassCastException
[org.json.simple.JSONObject cannot be cast to org.json.simple.JSONArray]
2015-12-15 21:34:06,315 INFO  c.c.d.c.team.TeamDataClientSetupImpl - Process took :0.881128951 seconds to update
2015-12-15 21:34:06,339 ERROR c.c.d.c.p.ProjectDataClientSetupImpl - There was a problem retrieving or parsing data from the local repository while retrieving a max change date
Returning null
projectinfo.st 1:40: \n in string
projectinfo.st 2:7: \n in string
projectinfo.st 3:7: \n in string
projectinfo.st 4:12: \n in string
projectinfo.st 5:10: \n in string
projectinfo.st 6:19: \n in string
projectinfo.st 7:13: \n in string
projectinfo.st 8:14: \n in string
projectinfo.st 9:12: \n in string
projectinfo.st 10:5: \n in string
projectinfo.st 11:9: \n in string
projectinfo.st 12:7: \n in string
projectinfo.st 13:28: \n in string
2015-12-15 21:34:06,496 ERROR c.c.d.c.p.ProjectDataClientSetupImpl - Unexpected error in VersionOne paging request of java.lang.ClassCastException
[org.json.simple.JSONObject cannot be cast to org.json.simple.JSONArray]
2015-12-15 21:34:06,497 INFO  c.c.d.c.p.ProjectDataClientSetupImpl - Process took :0.14364568 seconds to update
2015-12-15 21:34:06,521 ERROR c.c.d.c.s.FeatureDataClientSetupImpl - There was a problem retrieving or parsing data from the local repository while retrieving a max change date
Returning null
org.springframework.data.mongodb.UncategorizedMongoDbException: Query failed with error code 17287 and error message 'Can't canonicalize query: BadValue unknown top level operator: $query' on server ccloud-tomcat04200.kdc.capitalone.com:11500; nested exception is com.mongodb.MongoQueryException: Query failed with error code 17287 and error message 'Can't canonicalize query: BadValue unknown top level operator: $query' on server ccloud-tomcat04200.kdc.capitalone.com:11500
at org.springframework.data.mongodb.core.MongoExceptionTranslator.translateExceptionIfPossible(MongoExceptionTranslator.java:101) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.core.MongoTemplate.potentiallyConvertRuntimeException(MongoTemplate.java:2013) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1896) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1707) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.core.MongoTemplate.doFind(MongoTemplate.java:1690) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.core.MongoTemplate.find(MongoTemplate.java:602) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.repository.query.AbstractMongoQuery$Execution.readCollection(AbstractMongoQuery.java:170) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.repository.query.AbstractMongoQuery$CollectionExecution.execute(AbstractMongoQuery.java:193) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.mongodb.repository.query.AbstractMongoQuery.execute(AbstractMongoQuery.java:104) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:454) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:432) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61) ~[spring-data-commons-1.11.0.RELEASE.jar!/:na]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207) ~[spring-aop-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at com.sun.proxy.$Proxy38.getFeatureMaxChangeDate(Unknown Source) ~[na:na]
at com.capitalone.dashboard.client.story.FeatureDataClientSetupImpl.getMaxChangeDate(FeatureDataClientSetupImpl.java:193) ~[versionone-feature-collector.jar!/:1.5.0-SNAPSHOT]
at com.capitalone.dashboard.client.story.StoryDataClientImpl.updateStoryInformation(StoryDataClientImpl.java:368) [versionone-feature-collector.jar!/:1.5.0-SNAPSHOT]
at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:115) [versionone-feature-collector.jar!/:1.5.0-SNAPSHOT]
at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:28) [versionone-feature-collector.jar!/:1.5.0-SNAPSHOT]
at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) [core-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_25]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_25]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_25]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_25]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: com.mongodb.MongoQueryException: Query failed with error code 17287 and error message 'Can't canonicalize query: BadValue unknown top level operator: $query' on server ccloud-tomcat04200.kdc.capitalone.com:11500
at com.mongodb.connection.ProtocolHelper.getQueryFailureException(ProtocolHelper.java:93) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.connection.QueryProtocol.receiveMessage(QueryProtocol.java:288) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:229) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:38) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:155) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:219) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.connection.DefaultServerConnection.query(DefaultServerConnection.java:166) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.operation.FindOperation$1.call(FindOperation.java:397) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.operation.FindOperation$1.call(FindOperation.java:394) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:195) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:168) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.operation.FindOperation.execute(FindOperation.java:394) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.operation.FindOperation.execute(FindOperation.java:57) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.Mongo.execute(Mongo.java:738) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.Mongo$2.execute(Mongo.java:725) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.DBCursor.initializeCursor(DBCursor.java:815) ~[mongo-java-driver-3.0.2.jar!/:na]
at com.mongodb.DBCursor.hasNext(DBCursor.java:149) ~[mongo-java-driver-3.0.2.jar!/:na]
at org.springframework.data.mongodb.core.MongoTemplate.executeFindMultiInternal(MongoTemplate.java:1882) ~[spring-data-mongodb-1.8.0.RELEASE.jar!/:na]
... 29 common frames omitted
story.st 1:34: \n in string
story.st 2:7: \n in string
story.st 3:9: \n in string
story.st 4:7: \n in string
story.st 5:14: \n in string
story.st 6:13: \n in string
story.st 7:30: \n in string
story.st 8:11: \n in string
story.st 9:12: \n in string
story.st 10:13: \n in string
story.st 11:11: \n in string
story.st 12:13: \n in string
story.st 13:18: \n in string
story.st 14:16: \n in string
story.st 15:25: \n in string
story.st 16:19: \n in string
story.st 17:20: \n in string
story.st 18:18: \n in string
story.st 19:11: \n in string
story.st 20:13: \n in string
story.st 21:15: \n in string
story.st 22:40: \n in string
story.st 23:29: \n in string
story.st 24:21: \n in string
story.st 25:19: \n in string
story.st 26:22: \n in string
story.st 27:19: \n in string
story.st 28:19: \n in string
story.st 29:18: \n in string
story.st 30:13: \n in string
story.st 31:15: \n in string
story.st 32:20: \n in string
story.st 33:18: \n in string
story.st 34:21: \n in string
story.st 35:21: \n in string
story.st 36:20: \n in string
story.st 37:10: \n in string
story.st 38:12: \n in string
story.st 39:18: \n in string
story.st 40:18: \n in string
story.st 41:17: \n in string
story.st 42:12: \n in string
story.st 43:14: \n in string
story.st 44:18: \n in string
story.st 45:18: \n in string
story.st 46:20: \n in string
story.st 47:20: \n in string
story.st 48:19: \n in string
story.st 49:7: \n in string
story.st 50:29: \n in string
story.st 51:39: \n in string
2015-12-15 21:34:06,691 ERROR c.c.d.c.s.FeatureDataClientSetupImpl - Unexpected error in VersionOne paging request of java.lang.ClassCastException
[org.json.simple.JSONObject cannot be cast to org.json.simple.JSONArray]
2015-12-15 21:34:06,691 INFO  c.c.d.c.s.FeatureDataClientSetupImpl - Process took :0.134796839 seconds to update
2015-12-15 21:34:06,692 INFO  c.c.d.collector.FeatureCollectorTask - Feature Data Collection Finished

**Comment by hongluovz** [comment]
I was able to query jira by using jira-cli on the same server, so my jira access credential should be good. Here are all the config I have in application.properties file:
"spring.data.mongodb.database=dashboard
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=db
spring.data.mongodb.password=dbpass
feature.cron=0 * * * * *
feature.pageSize=1000
feature.queryFolder=jiraapi-queries
feature.projectQuery=ProjName
feature.deltaCollectorItemStartDate=2015-01-01T00:00:00.000000
feature.jiraBaseUrl=http://ourjira.ourcompany.com
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=username:password
feature.deltaStartDate=2015-03-01T00:00:00.000000
feature.masterStartDate=2015-03-01T00:00:00.000000"

I got these error now:
"2015-12-16 10:44:16,718 INFO  org.mongodb.driver.cluster - Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 0, 7]}, minWireVersion=0, maxWireVersion=3, electionId=null, maxDocumentSize=16777216, roundTripTimeNanos=1115153}
2015-12-16 10:44:16,980 INFO  org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:27}] to localhost:27017
2015-12-16 10:44:17,229 WARN  o.s.c.a.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'featureCollectorTask': Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1566) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299) ~[spring-beans-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
"

Thanks.

**Comment by amp5208** [comment]
Thank you for following up on this.  The issue you are seeing may be related to a defect found recently affecting the feature collectors, in general.  I am looking into this right now and will push a fix as soon as possible.
@amitmawkin :  Please mark this as a defect, related to the VersionOne Feature Collector defect with $query syntax

**Comment by hongluovz** [comment]
thank you.

**Comment by softwareklinic** [comment]
Same issue exists in Jira collector as well.

**Comment by amp5208** [comment]
Definitely see this, yes.  It seems to arose out of a change from the Java 1.7 to 1.8 framework for the Hygieia project; it would seem that certain repository query syntax I used is no longer supported in that version.

I am actively fixing now; hopefully I will have a fix within the next two weeks.  I apologize for any inconvenience this may have caused.

**Comment by hongluovz** [comment]
Just rebuild on a new server with JDK 1.8, I still got the same error. Thanks.

]$ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
$ uname -a
Linux scsblnx-295720.ebiz.verizon.com 3.10.0-229.7.2.el7.x86_64 #1 SMP Fri May 15 21:38:46 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by amp5208** [comment]
@hongluovz , Allow me to clarify:  The build was moved to a 1.8 JDK platform, which in turn broke the syntax in the FeatureCollector <code>@Query</code> annotations; however, the move to 1.8 may have also been required for some Core changes, and thus the build will no longer propagate as-is for 1.7, which the FeatureWidget code was original built/tested.  I am refactoring/making required code changes to ensure that the build works going forward for 1.8.

Until these changes are made, the FeatureCollectors will not build with either 1.7 or 1.8 and are broken.  I am working quickly to resolve these issues in the code.

**Comment by amp5208** [comment]
@hongluovz , As a follow-up, I wanted to let you know that a fix for this issue should be coming shortly.  I have pushed a fix as a pull request to fix the Feature collector compatibility issues.  Once it is fully validated, it should be pulled into Master.  You can view the pull request at the following link:  https://github.com/capitalone/Hygieia/pull/253

**Comment by Wills2607** [comment]
@amp5208 , Is this issue got fixed.?

**Comment by Wills2607** [comment]
I am getting this error, can you please help.?

-01-05 11:16:00,089 INFO  c.c.d.collector.FeatureCollectorTask - Starting Feature collection...
2016-01-05 11:16:00,255 ERROR c.c.d.c.team.TeamDataClientSetupImpl - There was a problem retrieving or parsing data from the local repository while retrieving a max change date
Returning null
2016-01-05 11:16:00,261 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at com.capitalone.dashboard.util.DateUtil.fromISODateTimeFormat(DateUtil.java:97) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.client.team.TeamDataClientSetupImpl.getChangeDateMinutePrior(TeamDataClientSetupImpl.java:133) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:112) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:97) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:24) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [na:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]

**Comment by amp5208** [comment]
@Wills2607 , Thank you for reaching out.  A fix has been provided in the above-noted pull request, but is not fully validated/merged yet.  Please check back when it is validated and merged.  The issue you are seeing is related to the defect or that you are missing a delta start date entry in your property file for the feature collectors.

**Comment by Wills2607** [comment]
Still same issue. Delta Date values in my properties  file.

feature.deltaStartDate=2016-01-01T00:00:00.000000
feature.masterStartDate=2016-01-01T00:00:00.000000

**Comment by amp5208** [comment]
Are you seeing the issue still with the most recent pull requested version referenced above?  As mentioned, there is a defect fix that is currently being implemented which may fix your issue.

**Comment by Wills2607** [comment]
Yes  - I have download from master repo yesterday, but still I am getting the same error.

**Comment by amp5208** [comment]
This defect fix is not yet in master - this may be your issue.  It is still under development, but if you want to validate that my defect fixes also fix your issue, please pull and check this forked version for now:  https://github.com/amp5208/Hygieia
Please note:  After the fix is merged to Capital One's org master, I will be destroying this fork.

**Comment by Wills2607** [comment]
Thank you, that got fixed. now I am getting different error. 

2016-01-06 14:07:00,255 ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task.
java.lang.NullPointerException: null
        at com.capitalone.dashboard.util.DateUtil.fromISODateTimeFormat(DateUtil.java:97) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.client.team.TeamDataClientSetupImpl.getChangeDateMinutePrior(TeamDataClientSetupImpl.java:132) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.client.team.TeamDataClientImpl.updateTeamInformation(TeamDataClientImpl.java:113) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:97) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashbo
ard.collector.FeatureCollectorTask.collect(FeatureCollectorTask.java:24) ~[jira-feature-collector.jar!/:1.5.0-SNAPSHOT]
        at com.capitalone.dashboard.collector.CollectorTask.run(CollectorTask.java:63) ~[core-1.5.0-SNAPSHOT.jar!/:1.5.0-SNAPSHOT]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81) [spring-context-4.1.7.RELEASE.jar!/:4.1.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java

**Comment by Wills2607** [comment]
can I have the working sample properties file ?

**Comment by Wills2607** [comment]
amp5208 :  can you pl help me if any thing wrong with   jira collector properties file.
===============

Properties file:-
feature.pageSize=1000

#
feature.queryFolder=jiraapi-queries
#
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=
feature.memberQuery=
feature.sprintQuery=
feature.teamQuery=
feature.trendingQuery=

#Jira
feature.jiraProxyUrl=
feature.jiraProxyPort=
######################
#
#
feature.sprintDays=60
#
feature.sprintEndPrior=7
######################
#Scheduled
feature.scheduledPriorMin=2
#Delta
#feature.deltaCollectorItemStartDate=2015-03-01T00:00:00.000000
feature.deltaCollectorItemStartDate=2008-01-01T00:00:00.000000


######################
#Spring
spring.data.mongodb.database=xxxx
spring.data.mongodb.host=xxxxxx
spring.data.mongodb.port=xxxxxxx
spring.data.mongodb.username=xxxxxxxx
spring.data.mongodb.password=xxxxxx


#Jira
feature.jiraBaseUrl=http://xxxx.com
feature.jiraQueryEndpoint=rest/api/2/
feature.jiraCredentials=xxxxxx:xxxxxxx
#feature.jiraOauthAuthtoken=oauth,
#feature.jiraOauthRefreshtoken=oauth,
#feature.jiraOauthRedirecturi=uri.this.is.test:uri
#feature.jiraOauthExpiretime=234567890987

######################
#Chron
feature.cron=0

#StartDate
feature.deltaStartDate=2015-03-01T00:00:00.000000

**Comment by Wills2607** [comment]
@amp5208 - Any update on this issue?

**Comment by amp5208** [comment]
Your issue is likely now that you have not updated your property files to handle for the new Jira configurations available in that version.  Please see the following link and ensure that you have the following feature.jira* properties:  https://github.com/amp5208/Hygieia/blob/master/jira-feature-collector/src/main/resources/jira-feature-collector.properties

<pre>
feature.jiraIssueTypeId=
feature.jiraSprintDataFieldName=
feature.jiraEpicIdFieldName=
</pre>

Additionally, I noticed in your above-noted property file that your Jira credentials property was malformed.  Jira credentials should be in username:password format, <strong>converted to a base64 string</strong>.  Please verify and try again.

**Comment by hongluovz** [comment]
@amp5208 Should we use applicattion.properties file to configure these attributes?

I finally got some jira projects back from our jira server, but always got only 5 projects although we have a lot more. These 5 projects were also duplicated many times in mongodb.
Below are some of my config in application.property file. Can I change the team or projectQuery to filter out some projects?
"#Convert above username:password into e64 bit string
feature.jiraCredentials=U1ZDLWh5Z2llaWEtamlyYTplVDIK
#In-built folder housing prepared REST queries (required)
feature.queryFolder=jiraapi-queries

#Jira API Query file names (String template requires the files to have .st extension) (required)
feature.storyQuery=story
feature.epicQuery=epic
feature.projectQuery=projectinfo
feature.memberQuery=memberinfo
feature.sprintQuery=sprintinfo
feature.teamQuery=teaminfo
feature.trendingQuery=trendinginfo"

Thanks.

**Comment by amp5208** [comment]
So long as you run the Jar with the name and location Springboot -D flags to reference your properties file, it does not matter if you place these arguments in the global application.properties or in a local jira-feature-collector.properties file.

However, please note, we are still fixing some bugs with this version that you are attempting to work with; until it is merged with master, it is considered volatile.  In particular, this working version is seeing the issue you described, where duplicate ScopeOwners (e.g., projects) will appear.

Lastly, you may want to remove the 64bit encoded string in your last comment...

**Comment by amp5208** [comment]
Fix is ready for your originally-noted issue - pending merge of https://github.com/capitalone/Hygieia/pull/253 pull request before closing this issue.  Once merged, please pull from master and use any new property file settings noted in the Feature content read-me's.

**Comment by amp5208** [comment]
This issue has been fixed.  @tabladrum or @amitmawkin , Please feel free to close this issue.

**Comment by SubramaniMurthy** [comment]
Hi,
I have configured JIRA Collector. And, collector is not throwing any error when i executing it.
It displays Agile Content Tool Type: Jira and all Project Names from JIRA tool in Feature Widget.

But, after selecting a project and saving the widget, it displays as _SPRINT: [NO SPRINT AVAILABLE]_ and everything with '0' value.

Would like to understand what would i have missed in the properties file. Please HELP !!!

Thanks,
Subbu

**Comment by amp5208** [comment]
@SubramaniMurthy , Thank you for reaching out, and I apologize for the delay.  I noticed this, myself, after a revert and re-merge activity that happened recently.  I believe that something in the API and/or Core was not properly pushed upstream during a pull request merge.

I plan on following up with this item as soon as possible and as soon as priorities allow me.

To verify, however, can you confirm with me your data within your MongoDB store?  Are you seeing data that should other wise map to the following scenario:  <em>An active Issue mapped to a status, mapped to an active Project, that is mapped to an active, in-progress Sprint?</em>  To validate this in the data, please check you <em>feature</em> MongoDB collection based on your Jira collector ID.

**Comment by amp5208** [comment]
@SubramaniMurthy, This issue has been continued in the following Issue post:  https://github.com/capitalone/Hygieia/issues/276.  I have also provided a concise "working" property example in that post.  Please reference that post for more information.

@tabladrum , This post can be closed in lieu of the related issue.

**Comment by atul1989** [comment]
credential is not working in JIRA , how can resolve
